export const calcBtns = [
  { id: "clear", label: "C" },
  { id: "backspace", label: "BS" },
  { id: "percent", label: "%" },
  { id: "divide", label: "/" },
  { id: "seven", label: "7" },
  { id: "eight", label: "8" },
  { id: "nine", label: "9" },
  { id: "multiply", label: "*" },
  { id: "four", label: "4" },
  { id: "five", label: "5" },
  { id: "six", label: "6" },
  { id: "minus", label: "-" },
  { id: "one", label: "1" },
  { id: "two", label: "2" },
  { id: "three", label: "3" },
  { id: "plus", label: "+" },
  { id: "zero", label: "0" },
  { id: "decimal", label: "." },
  { id: "equals", label: "=" },
];
